### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ruby0x1** [SavedByZero/openflump#1]
This link lists MIT, but the code itself has no license in the repo.

http://lib.haxe.org/p/openflump

[Might want to add one?](https://github.com/licenses/license-templates/blob/master/templates/mit.txt)

**Comment by Justinfront** [comment]
yep would be good I was thinking about possibilities of native haxe js and luxe, also can flump can have a MIT license as well, apparently it's not at the moment?

**Comment by ruby0x1** [comment]
(Flump license isn't related to this repo/author at all)

**Comment by Justinfront** [comment]
Ah I miss read this.
"OpenFL parser for Flump. Flump was created at Three Rings by Charlie Groves, Tim Conkling, and Bruno Garcia."
Assuming it was 3rings related.

I have asked flump directly as I think it would be useful/ideal if they are also MIT.
https://github.com/threerings/flump/issues/137

**Comment by SavedByZero** [comment]
Added the file, sorry for my forgetfulness.
